"""Helpers for the Lane Editor page.

Turns a tracks.csv (produced by detection/tracking) into an editable set of lane
boxes: auto-clusters the vehicle motion into N travel directions, builds an
axis-aligned box + mean heading per direction, and round-trips to the GeoJSON
format consumed by wwd_detection / geometry_config.
"""
import json

import numpy as np
import pandas as pd
import plotly.graph_objects as go
from sklearn.cluster import KMeans


def load_tracks(source) -> pd.DataFrame:
    """Read a tracks.csv (path or uploaded buffer). Ensures a 'heading' column:
    if absent/NaN it is recomputed from vx, vy."""
    df = pd.read_csv(source)
    if 'heading' not in df.columns:
        df['heading'] = np.nan
    need = df['heading'].isna()
    if need.any() and {'vx', 'vy'}.issubset(df.columns):
        df.loc[need, 'heading'] = np.arctan2(
            pd.to_numeric(df.loc[need, 'vy'], errors='coerce'),
            pd.to_numeric(df.loc[need, 'vx'], errors='coerce'),
        )
    return df


def moving_points(df: pd.DataFrame, min_speed: float = 1.0) -> np.ndarray:
    """(N, 3) array of [cx, cy, heading_rad] for moving rows with valid heading."""
    d = df
    if 'speed' in d.columns:
        d = d[pd.to_numeric(d['speed'], errors='coerce') >= min_speed]
    d = d[d['heading'].notna()]
    if len(d) == 0:
        return np.zeros((0, 3))
    return d[['cx', 'cy', 'heading']].to_numpy(dtype=float)


def auto_lanes(points: np.ndarray, k: int = 4, buffer_m: float = 2.0):
    """Cluster motion into k travel directions; one axis-aligned lane box per
    cluster (bounding box of its points + buffer, circular-mean heading)."""
    lanes = []
    if len(points) == 0:
        return lanes
    k = max(1, min(k, len(points)))
    H = points[:, 2]
    feats = np.column_stack([np.cos(H), np.sin(H)])  # cluster on direction only
    labels = KMeans(n_clusters=k, n_init=10, random_state=0).fit(feats).labels_
    for c in range(k):
        pts = points[labels == c]
        if len(pts) == 0:
            continue
        # Robust circular mean of the travel heading: start from the plain mean,
        # then iteratively drop points whose heading is far from it. TURNING
        # vehicles sweep through headings and would otherwise pull the lane's
        # direction diagonal — this keeps it on the straight-through flow.
        Hc = pts[:, 2]
        mh = np.arctan2(np.sin(Hc).mean(), np.cos(Hc).mean())
        for _ in range(4):
            dev = np.abs((np.degrees(Hc - mh) + 180.0) % 360.0 - 180.0)
            keep = dev <= 30.0
            if keep.sum() >= max(5, int(0.25 * len(Hc))):
                mh = np.arctan2(np.sin(Hc[keep]).mean(), np.cos(Hc[keep]).mean())
        lanes.append(dict(
            lane_id=f"lane_{c+1}",
            xmin=float(pts[:, 0].min() - buffer_m), xmax=float(pts[:, 0].max() + buffer_m),
            ymin=float(pts[:, 1].min() - buffer_m), ymax=float(pts[:, 1].max() + buffer_m),
            heading_deg=float(np.degrees(mh)), n=int(len(pts)),
        ))
    lanes.sort(key=lambda l: -l['n'])
    return lanes


def snap_to_cardinal(deg: float) -> float:
    """Nearest cardinal heading to `deg` (E=0°, N=90°, W=180°, S=−90°), in degrees —
    so the lane arrow points straight along an axis, ignoring vehicle scatter."""
    cards = [0.0, 90.0, 180.0, -90.0]
    return float(min(cards, key=lambda c: abs((float(deg) - c + 180.0) % 360.0 - 180.0)))


def lanes_to_geojson(lanes) -> dict:
    feats = []
    for l in lanes:
        xmin, xmax = sorted((float(l['xmin']), float(l['xmax'])))
        ymin, ymax = sorted((float(l['ymin']), float(l['ymax'])))
        ring = [[xmin, ymin], [xmax, ymin], [xmax, ymax], [xmin, ymax], [xmin, ymin]]
        feats.append({
            "type": "Feature",
            "properties": {"lane_id": str(l['lane_id']),
                           "heading_deg": round(float(l['heading_deg']), 1),
                           "calibrated": True},
            "geometry": {"type": "Polygon", "coordinates": [ring]},
        })
    return {"type": "FeatureCollection",
            "_comment": "Generated by the Lane Editor page.",
            "features": feats}


def geojson_to_lanes(gj: dict):
    """Inverse of lanes_to_geojson, for loading an existing config to edit."""
    lanes = []
    for f in gj.get('features', []):
        p = f.get('properties', {})
        ring = f['geometry']['coordinates'][0]
        xs = [c[0] for c in ring]
        ys = [c[1] for c in ring]
        lanes.append(dict(lane_id=p.get('lane_id', f"lane_{len(lanes)+1}"),
                          xmin=min(xs), xmax=max(xs), ymin=min(ys), ymax=max(ys),
                          heading_deg=float(p.get('heading_deg', 0.0)), n=0))
    return lanes


_PALETTE = ['#1f77b4', '#9467bd', '#17becf', '#e377c2', '#bcbd22',
            '#7f7f7f', '#ff7f0e', '#2ca02c']

# Cardinal buckets in the sensor frame (atan2(vy,vx) degrees). Named by axis AND
# the lane convention so the legend is unambiguous (note: +Y is the sensor's
# axis, only "north" by convention — not verified geographic north).
_CARDINAL = [
    ("E  (+X, ~0°)",   '#d62728'),
    ("N  (+Y, ~90°)",  '#2ca02c'),
    ("W  (-X, ~180°)", '#1f77b4'),
    ("S  (-Y, ~-90°)", '#ff7f0e'),
]


def _cardinal_bucket(deg: np.ndarray) -> np.ndarray:
    d = (np.asarray(deg, dtype=float) + 180.0) % 360.0 - 180.0  # -> [-180, 180)
    lab = np.empty(d.shape, dtype=object)
    lab[(d >= -45) & (d < 45)] = _CARDINAL[0][0]
    lab[(d >= 45) & (d < 135)] = _CARDINAL[1][0]
    lab[(d >= 135) | (d < -135)] = _CARDINAL[2][0]
    lab[(d >= -135) & (d < -45)] = _CARDINAL[3][0]
    return lab


def load_pcd_background(pcd_dir: str, n_frames: int = 15, grid: float = 0.5,
                        max_points: int = 60000) -> np.ndarray:
    """Accumulate an (X, Y, Z) road footprint from several PCD frames,
    grid-downsampled in XY, for a faint backdrop in the editor preview."""
    import glob
    import os
    import open3d as o3d
    files = sorted(glob.glob(os.path.join(pcd_dir, '*.pcd')))
    if not files:
        return np.zeros((0, 3))
    idxs = np.unique(np.linspace(0, len(files) - 1, min(n_frames, len(files))).astype(int))
    acc = []
    for i in idxs:
        pts = np.asarray(o3d.io.read_point_cloud(files[int(i)]).points)
        if pts.size:
            acc.append(pts[:, :3])
    if not acc:
        return np.zeros((0, 3))
    xyz = np.vstack(acc)
    _, idx = np.unique(np.floor(xyz[:, :2] / grid).astype(np.int64), axis=0, return_index=True)
    xyz = xyz[idx]
    if len(xyz) > max_points:
        xyz = xyz[np.random.choice(len(xyz), max_points, replace=False)]
    return xyz


def assign_points_to_lanes(points: np.ndarray, lanes) -> np.ndarray:
    """First-match lane index for each point (axis-aligned box test); -1 if the
    point is outside every lane box."""
    n = len(points)
    a = np.full(n, -1, dtype=int)
    if n == 0:
        return a
    x, y = points[:, 0], points[:, 1]
    for i, l in enumerate(lanes):
        xmin, xmax = sorted((float(l['xmin']), float(l['xmax'])))
        ymin, ymax = sorted((float(l['ymin']), float(l['ymax'])))
        m = (a < 0) & (x >= xmin) & (x <= xmax) & (y >= ymin) & (y <= ymax)
        a[m] = i
    return a


def lane_display_colors(lanes, color_mode: str):
    """One display color per lane, chosen so boxes match the vehicle dots:
    'lane' -> per-lane palette; otherwise -> the lane heading's cardinal color."""
    card = dict(_CARDINAL)
    cols = []
    for i, l in enumerate(lanes):
        if color_mode == 'lane':
            cols.append(_PALETTE[i % len(_PALETTE)])
        else:
            lab = _cardinal_bucket(np.array([l['heading_deg']]))[0]
            cols.append(card.get(lab, '#888888'))
    return cols


def build_preview(points: np.ndarray, lanes, color_mode: str = 'cardinal',
                  bg_xyz: np.ndarray = None, top_down: bool = True,
                  hdmap_lanes=None) -> go.Figure:
    """3D bird's-eye preview (same mouse UX as the detection viewer): optional
    point-cloud backdrop + vehicle positions + lane boxes with direction arrows.
    Box colors always match the dot colors. ``top_down`` toggles the camera.

    ``hdmap_lanes`` (list of sensor-frame polylines [[x, y], ...]) draws the real
    intersection's HD-map road network underneath, so lane boxes can be aligned to
    the actual roads.

    color_mode: 'cardinal' (dots by direction bucket), 'lane' (dots by which box
    they fall in; gray if outside all), or 'heading' (continuous HSV)."""
    Z_DOT, Z_BOX = -6.0, -7.2
    fig = go.Figure()

    # Real intersection roads (HD map) — one batched trace, under everything.
    if hdmap_lanes:
        hx, hy, hz = [], [], []
        for poly in hdmap_lanes:
            for px, py in poly:
                hx.append(float(px)); hy.append(float(py)); hz.append(Z_BOX)
            hx.append(None); hy.append(None); hz.append(None)
        fig.add_trace(go.Scatter3d(
            x=hx, y=hy, z=hz, mode='lines', line=dict(color='#5b6573', width=1),
            opacity=0.65, name='intersection (HD map)', hoverinfo='skip'))

    if bg_xyz is not None and len(bg_xyz):
        bg_xyz = np.asarray(bg_xyz)
        # Tolerate a 2-column (X,Y) background (e.g. an older cached result) by
        # placing it on the box plane instead of crashing on a missing Z column.
        bz = bg_xyz[:, 2] if bg_xyz.shape[1] >= 3 else np.full(len(bg_xyz), Z_BOX)
        fig.add_trace(go.Scatter3d(
            x=bg_xyz[:, 0], y=bg_xyz[:, 1], z=bz, mode='markers',
            marker=dict(size=1.5, color='#9a9a9a', opacity=0.35),
            name='point cloud', hoverinfo='skip'))

    lane_cols = lane_display_colors(lanes, color_mode)

    if len(points):
        zc = np.full(len(points), Z_DOT)
        if color_mode == 'cardinal':
            buckets = _cardinal_bucket(np.degrees(points[:, 2]))
            for label, col in _CARDINAL:
                m = buckets == label
                if m.any():
                    fig.add_trace(go.Scatter3d(
                        x=points[m, 0], y=points[m, 1], z=zc[m], mode='markers',
                        marker=dict(size=3, color=col), name=label, hoverinfo='skip'))
        elif color_mode == 'lane':
            assign = assign_points_to_lanes(points, lanes)
            m = assign < 0
            if m.any():
                fig.add_trace(go.Scatter3d(
                    x=points[m, 0], y=points[m, 1], z=zc[m], mode='markers',
                    marker=dict(size=3, color='#cccccc'),
                    name='outside any lane', hoverinfo='skip'))
            for i, l in enumerate(lanes):
                m = assign == i
                if m.any():
                    fig.add_trace(go.Scatter3d(
                        x=points[m, 0], y=points[m, 1], z=zc[m], mode='markers',
                        marker=dict(size=3, color=lane_cols[i]),
                        name=str(l['lane_id']), hoverinfo='skip'))
        else:
            fig.add_trace(go.Scatter3d(
                x=points[:, 0], y=points[:, 1], z=zc, mode='markers',
                marker=dict(size=3, color=np.degrees(points[:, 2]), colorscale='HSV',
                            cmin=-180, cmax=180, colorbar=dict(title='heading°')),
                name='vehicle positions', hoverinfo='skip'))

    for i, l in enumerate(lanes):
        col = lane_cols[i]
        xmin, xmax = sorted((float(l['xmin']), float(l['xmax'])))
        ymin, ymax = sorted((float(l['ymin']), float(l['ymax'])))
        fig.add_trace(go.Scatter3d(
            x=[xmin, xmax, xmax, xmin, xmin], y=[ymin, ymin, ymax, ymax, ymin],
            z=[Z_BOX] * 5, mode='lines', line=dict(color=col, width=5),
            name=str(l['lane_id'])))
        cx, cy = (xmin + xmax) / 2.0, (ymin + ymax) / 2.0
        hd = np.radians(float(l['heading_deg']))
        L = 0.4 * min(xmax - xmin, ymax - ymin) + 3.0
        tx, ty = cx + L * np.cos(hd), cy + L * np.sin(hd)
        fig.add_trace(go.Scatter3d(x=[cx, tx], y=[cy, ty], z=[Z_BOX, Z_BOX],
                                   mode='lines', line=dict(color=col, width=6),
                                   showlegend=False, hoverinfo='skip'))
        wl, wa = 2.4, np.radians(28)
        fig.add_trace(go.Scatter3d(
            x=[tx - wl * np.cos(hd - wa), tx, tx - wl * np.cos(hd + wa)],
            y=[ty - wl * np.sin(hd - wa), ty, ty - wl * np.sin(hd + wa)],
            z=[Z_BOX] * 3, mode='lines', line=dict(color=col, width=6),
            showlegend=False, hoverinfo='skip'))

    if top_down:
        cam = {'up': {'x': 0, 'y': 1, 'z': 0}, 'center': {'x': 0, 'y': 0, 'z': 0},
               'eye': {'x': 0, 'y': 0, 'z': 2.6}}
    else:
        cam = {'up': {'x': 0, 'y': 0, 'z': 1}, 'center': {'x': 0, 'y': 0, 'z': 0},
               'eye': {'x': 1.55, 'y': 1.55, 'z': 1.55}}
    # uirevision keeps the user's zoom/rotation across Streamlit reruns (e.g.
    # while editing box numbers); it only resets when the camera mode changes.
    uirev = f"td_{top_down}"
    # Default to a zoomed-OUT view (the whole intersection / research region) so it
    # doesn't sit tight on just the lanes when the point-cloud backdrop is off.
    try:
        from geometry_config import get_research_polygon
        bx0, by0, bx1, by1 = get_research_polygon().bounds
        m = 5.0
        xrange, yrange = [bx0 - m, bx1 + m], [by0 - m, by1 + m]
    except Exception:
        xrange = yrange = None
    fig.update_layout(
        height=680, margin=dict(l=0, r=0, t=30, b=0),
        uirevision=uirev,
        scene=dict(xaxis=dict(title='X (m)', range=xrange), yaxis=dict(title='Y (m)', range=yrange),
                   zaxis_title='Z (m)', aspectmode='data', camera=cam, uirevision=uirev),
        legend=dict(orientation='h', y=-0.02),
        title='Top-down (drag to rotate, scroll to zoom, right-drag to pan)' if top_down else '3D view')
    return fig
